version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn -f backend/WeatherForecast/demo/pom.xml clean package

  docker-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            cd backend/WeatherForecast/demo
            docker build -t weather-forecast-app .

workflows:
  version: 2
  build_and_dockerize:
    jobs:
      - build
      - docker-build:
          requires:
            - build
